spring.application.name=EquipoVirtual6

spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost/AndiaBDPC2
spring.datasource.username=postgres
spring.datasource.password=60772554